name: /common/users/dm1487/envs/arcmg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=2.131=openblas
  - blas-devel=3.9.0=31_h1ea3ea9_openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - gmp=6.2.1=h58526e2_0
  - lapack=3.6.1=ha44fe06_2
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libopenblas=0.3.29=ha39b09d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - metis=5.1.0=h58526e2_1006
  - mpfr=4.1.0=h9202a9a_1
  - ncurses=6.4=h6a678d5_0
  - nomkl=3.0=0
  - openblas=0.3.29=h06a4308_0
  - openblas-devel=0.3.29=ha39b09d_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - suitesparse=5.10.1=h9e50725_1
  - tbb=2021.5.0=h924138e_1
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - alembic==1.16.5
      - antlr4-python3-runtime==4.9.3
      - arcmg==0.0.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - black==25.1.0
      - bottle==0.13.4
      - casadi==3.7.2
      - cffi==2.0.0
      - cfgv==3.4.0
      - clarabel==0.11.1
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cvxpy==1.7.3
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - dict-deep==4.1.2
      - distlib==0.4.0
      - etils==1.13.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.7.0
      - fsspec==2024.12.0
      - glfw==2.9.0
      - gpytorch==1.13
      - greenlet==3.2.4
      - grpcio==1.74.0
      - gymnasium==0.28.1
      - hydra-core==1.3.2
      - identify==2.6.15
      - idna==3.10
      - igraph==0.11.8
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipympl==0.9.6
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - jax-jumpy==1.0.0
      - jaxtyping==0.2.19
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - libcst==1.8.4
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - linear-operator==0.5.3
      - lxml==6.0.1
      - mako==1.3.10
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - moreorless==0.5.0
      - mosek==10.2.17
      - mpmath==1.3.0
      - mujoco==3.3.4
      - multidict==6.6.3
      - munch==2.5.0
      - mypy-extensions==1.1.0
      - mysql-connector-python==8.0.33
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - optuna==3.6.2
      - optuna-dashboard==0.9.2
      - osqp==1.0.4
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pastel==0.2.1
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pluggy==1.6.0
      - poethepoet==0.10.0
      - pot==0.9.5
      - pre-commit==3.8.0
      - prompt-toolkit==3.0.50
      - propcache==0.3.2
      - protobuf==3.20.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyaml==25.7.0
      - pybind11==3.0.1
      - pybullet==3.2.7
      - pycddlib==2.1.8.post1
      - pycparser==2.23
      - pygments==2.19.1
      - pymysql==1.1.1
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - pytest==7.4.4
      - python-dateutil==2.9.0.post0
      - pytope==0.0.4
      - pytorch-lightning==2.5.2
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - safe-control-gym==2.0.0
      - scikit-learn==1.6.0
      - scikit-optimize==0.9.0
      - scikit-sparse==0.4.16
      - scipy==1.15.0
      - scs==3.2.8
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - six==1.17.0
      - sqlalchemy==2.0.43
      - stack-data==0.6.3
      - stdlibs==2025.5.10
      - sympy==1.14.0
      - tenacity==9.0.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==1.1.0
      - texttable==1.7.0
      - theseus-ai==0.2.3
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.8.0
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchkin==0.1.1
      - torchlie==0.1.0
      - torchmetrics==1.8.0
      - torchsde==0.2.6
      - torchvision==0.23.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - trailrunner==1.4.0
      - traitlets==5.14.3
      - trampoline==0.1.2
      - triton==3.4.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tzdata==2024.2
      - ufmt==2.3.0
      - urdf-parser-py==0.0.4
      - usort==1.0.4
      - virtualenv==20.34.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /common/users/dm1487/envs/arcmg
