# Mountain Car System Configuration

_target_: src.systems.mountain_car.MountainCarSystem
bounds_file: /common/users/dm1487/arcmg_datasets/mountain_car_power_0p0008/mountain_car_data_bounds.pkl
use_dynamic_bounds: false
